/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import algo.Decrypt;
import algo.Encrypt;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.filechooser.FileFilter;

/**
 *
 * @author Thilina Prasad
 */
public class Crypto extends javax.swing.JFrame {

    ArrayList<String> readedData = new ArrayList<>();
    ArrayList<String> dataTowrite;
    String seperator = "";

    /**
     * Creates new form Crypto
     */
    public Crypto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        openedFile = new javax.swing.JLabel();
        messeages1 = new javax.swing.JLabel();
        messeages = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        key = new javax.swing.JTextField();
        saveBtn = new javax.swing.JLabel();
        decBtn = new javax.swing.JLabel();
        encBtn = new javax.swing.JLabel();
        openBtn = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel2.setLayout(null);

        openedFile.setFont(new java.awt.Font("Garamond", 1, 12)); // NOI18N
        openedFile.setForeground(new java.awt.Color(0, 255, 0));
        openedFile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(openedFile);
        openedFile.setBounds(20, 280, 280, 10);

        messeages1.setFont(new java.awt.Font("Garamond", 1, 12)); // NOI18N
        messeages1.setForeground(new java.awt.Color(255, 255, 255));
        messeages1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        messeages1.setText("Crypt Key");
        jPanel2.add(messeages1);
        messeages1.setBounds(70, 210, 170, 15);

        messeages.setFont(new java.awt.Font("Garamond", 1, 12)); // NOI18N
        messeages.setForeground(new java.awt.Color(255, 255, 255));
        messeages.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(messeages);
        messeages.setBounds(10, 450, 300, 20);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/close_1.png"))); // NOI18N
        jLabel8.setToolTipText("Minimize");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel8MouseExited(evt);
            }
        });
        jPanel2.add(jLabel8);
        jLabel8.setBounds(260, 8, 24, 24);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/close_1.png"))); // NOI18N
        jLabel6.setToolTipText("Close");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel6MouseExited(evt);
            }
        });
        jPanel2.add(jLabel6);
        jLabel6.setBounds(288, 8, 24, 24);

        key.setBackground(new java.awt.Color(0, 0, 37));
        key.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        key.setForeground(new java.awt.Color(255, 255, 255));
        key.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        key.setToolTipText("Crypt Key");
        key.setBorder(null);
        key.setCaretColor(new java.awt.Color(255, 255, 255));
        key.setOpaque(false);
        jPanel2.add(key);
        key.setBounds(60, 230, 200, 40);

        saveBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/SAVE FILE_1.png"))); // NOI18N
        saveBtn.setText("jLabel5");
        saveBtn.setToolTipText("Save crypted data");
        saveBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        saveBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                saveBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                saveBtnMouseExited(evt);
            }
        });
        jPanel2.add(saveBtn);
        saveBtn.setBounds(40, 400, 240, 45);

        decBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/DECRYPT_1.png"))); // NOI18N
        decBtn.setText("jLabel4");
        decBtn.setToolTipText("Decrypt");
        decBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        decBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                decBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                decBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                decBtnMouseExited(evt);
            }
        });
        jPanel2.add(decBtn);
        decBtn.setBounds(165, 345, 120, 45);

        encBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/ENCRYPT_1.png"))); // NOI18N
        encBtn.setText("jLabel2");
        encBtn.setToolTipText("Encrypt");
        encBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        encBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                encBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                encBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                encBtnMouseExited(evt);
            }
        });
        jPanel2.add(encBtn);
        encBtn.setBounds(40, 345, 120, 45);

        openBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/OPEN FILE_1.png"))); // NOI18N
        openBtn.setText("jLabel3");
        openBtn.setToolTipText("Open file");
        openBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        openBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                openBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                openBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                openBtnMouseExited(evt);
            }
        });
        jPanel2.add(openBtn);
        openBtn.setBounds(40, 290, 240, 45);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/320x480.jpg"))); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(0, 0, 320, 480);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void openBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_openBtnMouseEntered
        openBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/OPEN FILE_2.png")));
    }//GEN-LAST:event_openBtnMouseEntered

    private void encBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_encBtnMouseEntered
        encBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/ENCRYPT_2.png")));
    }//GEN-LAST:event_encBtnMouseEntered

    private void encBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_encBtnMouseExited
        encBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/ENCRYPT_1.png")));
    }//GEN-LAST:event_encBtnMouseExited

    private void decBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_decBtnMouseEntered
        decBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/DECRYPT_2.png")));
    }//GEN-LAST:event_decBtnMouseEntered

    private void decBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_decBtnMouseExited
        decBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/DECRYPT_1.png")));
    }//GEN-LAST:event_decBtnMouseExited

    private void saveBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveBtnMouseEntered
        saveBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/SAVE FILE_2.png")));
    }//GEN-LAST:event_saveBtnMouseEntered

    private void saveBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveBtnMouseExited
        saveBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/SAVE FILE_1.png")));
    }//GEN-LAST:event_saveBtnMouseExited

    private void openBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_openBtnMouseExited
        openBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/OPEN FILE_1.png")));
    }//GEN-LAST:event_openBtnMouseExited

    private void jLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseEntered
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/close_2.png")));
    }//GEN-LAST:event_jLabel6MouseEntered

    private void jLabel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseExited
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/close_1.png")));
    }//GEN-LAST:event_jLabel6MouseExited

    private void jLabel8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseExited
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/close_1.png")));
    }//GEN-LAST:event_jLabel8MouseExited

    private void jLabel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseEntered
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/minimize.png")));
    }//GEN-LAST:event_jLabel8MouseEntered

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        System.exit(1);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void openBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_openBtnMouseClicked
        JFileChooser chooser = new JFileChooser();
        chooser.setFileFilter(new TextFileFilter());
        int result = chooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File f = chooser.getSelectedFile();
            String filePath = f.getAbsolutePath();
            System.out.println(f.getName());
            FileReader fr;
            
            try {
                fr = new FileReader(f);
                BufferedReader br = new BufferedReader(fr);
                String temp;
                while ((temp = br.readLine()) != null) {
                    //String temp = br.readLine();
                    readedData.add(temp);
                }
                System.out.println(readedData.toString());
                br.close();
                openedFile.setText(f.getName());
                messeages.setText("Successfully Opened!");
            } catch (FileNotFoundException ex) {

            } catch (IOException ex) {

            }
            //path.setText(readedData.toString());
        } else if (result == JFileChooser.CANCEL_OPTION) {
            chooser.disable();
        }
    }//GEN-LAST:event_openBtnMouseClicked

    private void saveBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveBtnMouseClicked
        //System.out.println(dataTowrite.toString());
        //if (dataTowrite.isEmpty()) {
        JFileChooser chooser = new JFileChooser();
        //chooser.setFileFilter(new TextFileFilter());
        chooser.setDialogTitle("File save path");
        //chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int result = chooser.showSaveDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            try {
                File f = chooser.getSelectedFile();
                //File f = new File(operation + ".txt");
                FileWriter fr;
                fr = new FileWriter(f);
                BufferedWriter br = new BufferedWriter(fr);
                //System.out.println(dataTowrite.toString());

                for (int i = 0; i < dataTowrite.size(); i++) {
                    br.write(dataTowrite.get(i));
                    br.newLine();
                }

                br.close();
                readedData.clear();
                dataTowrite.clear();
                openedFile.setText("Select another file!");
                messeages.setText("Successfully saved to file!");
            } catch (IOException e) {
            }
        } else if (result == JFileChooser.CANCEL_OPTION) {
            chooser.disable();
        }
        /*} else {
                    messeages.setText("Do operation before save!");

                }*/
    }//GEN-LAST:event_saveBtnMouseClicked

    private void encBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_encBtnMouseClicked
        //System.out.println(!key.getText().equals(""));
        if (!key.getText().trim().equals("")) {
            messeages.setText("Encrypting...");
            Encrypt enc = new Encrypt();
            dataTowrite = enc.encrypt(key.getText(), readedData);

            messeages.setText("Successfully encrypted!");
        } else {
            messeages.setText("Please Enter crypt key!");

        }
    }//GEN-LAST:event_encBtnMouseClicked

    private void decBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_decBtnMouseClicked
        if (!key.getText().trim().equals("")) {
            messeages.setText("Decrypting...");
            Decrypt dec = new Decrypt();
            dataTowrite = dec.decrypt(key.getText(), readedData);
            messeages.setText("Successfully decrypted!");
        } else {
            messeages.setText("Please Enter crypt key!");

        }
    }//GEN-LAST:event_decBtnMouseClicked
//

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

 /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Crypto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel decBtn;
    private javax.swing.JLabel encBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField key;
    private javax.swing.JLabel messeages;
    private javax.swing.JLabel messeages1;
    private javax.swing.JLabel openBtn;
    private javax.swing.JLabel openedFile;
    private javax.swing.JLabel saveBtn;
    // End of variables declaration//GEN-END:variables

    private static class TextFileFilter extends FileFilter {

        public TextFileFilter() {
        }

        public boolean accept(File file) {
            // Allow only directories, or files with ".txt" extension
            return file.isDirectory() || file.getAbsolutePath().endsWith(".txt");
        }

        @Override
        public String getDescription() {
            // This description will be displayed in the dialog,
            // hard-coded = ugly, should be done via I18N
            return "Text documents (*.txt)";
        }
    }
}
